function baseName = getRunBaseName(projectName, cellTypes,runNumber, nB, nD)

baseName  = fullfile(pwd, 'results',projectName, ...
    ['nB' num2str(nB) '_nD'  num2str(nD)], ['run' num2str(runNumber)],...
    ['train_' 'run' num2str(runNumber) '_' cell2mat(cellTypes) '_nD' num2str(nD) '_nB' num2str(nB)]);
